[package]
name = "cocko-rs"
version = "0.1.0"
authors = ["kwangin.jung <inylove82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
tokio = "0.1.18"
futures = "0.1.21"
